export const DEFAULT_DIFF_RENDER_LINE_COUNT = 600;
export const MIN_DIFF_RENDER_LINE_COUNT = 100;
export const MAX_DIFF_RENDER_LINE_COUNT = 2_000;
export const DEFAULT_DIFF_VIEWPORT_HEIGHT_PX = 640;
export const DEFAULT_DIFF_ROW_HEIGHT_PX = 28;
export const DEFAULT_WRAPPED_DIFF_ROW_HEIGHT_PX = 112;
export const MIN_DIFF_ROW_HEIGHT_PX = 24;
export const MAX_DIFF_ROW_HEIGHT_PX = 180;
export const DEFAULT_DIFF_OVERSCAN_LINE_COUNT = 8;

