use argon2::password_hash::{PasswordHash, PasswordHasher, PasswordVerifier, SaltString};
use argon2::{Argon2, password_hash::rand_core::OsRng};
use axum::body::{Body, Bytes};
use axum::extract::{DefaultBodyLimit, Form, Path, Query, State};
use axum::http::header::{AUTHORIZATION, CONTENT_TYPE, COOKIE, SET_COOKIE};
use axum::http::{HeaderMap, HeaderValue, Method, StatusCode};
use axum::response::{Html, IntoResponse, Response};
use axum::routing::{delete, get, patch, post, put};
use axum::{Json, Router};
use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use serde::Deserialize;
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use sqlx::postgres::PgPoolOptions;
use sqlx::{PgPool, Row};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::net::SocketAddr;
use tower_http::cors::CorsLayer;
use uuid::Uuid;

use crate::{AuthRequirement, HttpMethod, ROUTES, RouteDescriptor};

mod access;
mod auth;
mod devices;
mod layers;
mod repository;
mod spaces;
mod studio;
mod teams;
mod workspaces;

static MIGRATOR: sqlx::migrate::Migrator = sqlx::migrate!("../layrs-store-server/migrations");

const SESSION_COOKIE_NAME: &str = "layrs_session";
const SESSION_MAX_AGE_SECONDS: i64 = 7 * 24 * 60 * 60;
const DESKTOP_TOKEN_EXPIRES_SECONDS: i64 = 30 * 24 * 60 * 60;
const DEVICE_FLOW_EXPIRES_SECONDS: i64 = 10 * 60;
const DEVICE_FLOW_POLL_INTERVAL_SECONDS: i64 = 2;
const DEFAULT_ARTIFACT_DIFF_WINDOW_LIMIT: usize = 400;
const MAX_ARTIFACT_DIFF_WINDOW_LIMIT: usize = 1000;
const MAX_DIFF_COLUMN_WINDOW_LIMIT: usize = 4000;
const MAX_REQUEST_BODY_BYTES: usize = 32 * 1024 * 1024;
const CHUNK_COMPRESSION_IDENTITY: &str = "identity";
const CHUNK_COMPRESSION_ZSTD: &str = "zstd";

include!("sections/routing.rs");
include!("sections/auth_handlers.rs");
include!("sections/workspace_team_handlers.rs");
include!("sections/space_layer_handlers.rs");
include!("sections/studio_sync_handlers.rs");
include!("sections/timeline_artifact_access_handlers.rs");
include!("sections/device_handlers.rs");
include!("sections/session_authz.rs");
include!("sections/snapshot_values.rs");
include!("sections/step_tree_values.rs");
include!("sections/workspace_invitation_values.rs");
include!("sections/artifact_lens_values.rs");
include!("sections/access_timeline_values.rs");
include!("sections/store_objects.rs");
include!("sections/artifact_publish.rs");
include!("sections/layer_state_publish.rs");
include!("sections/weave_handlers.rs");
include!("sections/devices_audit_policy.rs");
include!("sections/wire_utils.rs");
include!("sections/store_object_bodies.rs");
include!("sections/tests.rs");
